### ISSUE TITLE
Error creating project with "forceios". 

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#2186]
Please fill out the following details:

1. Version of Mobile SDK Used: The versión used by forceios
2. Issue found in Native App or Hybrid App: Native
3. OS Version: macOS Sierra Versión 10.12.6
4. Device: iPhone and iPad
5. Steps to reproduce: Create project with forceios. Build and Run.
6. Actual behavior: Error
7. Expected Behavior: Project without errors
8. Error Log:
I obtain two errors:
"Too many arguments to function call, expected single argument 'pStmt', have 3 arguments"
"Implicit declaration of function 'sqlite3_key' is invalid in C99"

Hello all.

I only want to create an iOS project with Salesforce SDK.
I update npm forceios and I update git on my Mac.

I use forceios and the tool creates a project correctly.

I open the workspace file with XCode. I compile and run the project.
The project didn't compile, I obtain two errors:
"Too many arguments to function call, expected single argument 'pStmt', have 3 arguments"
"Implicit declaration of function 'sqlite3_key' is invalid in C99"

How can I solve it?

Thanks.

**Comment by wmathurin** [comment]
It doesn't compile with Xcode 9. Please use Xcode 8 for now.
We have fixed the issue in the dev branch and it will be part of our upcoming release.

**Comment by CesarRN** [comment]
...

¿Salesforce SDK is compatible with iOS 11?

Thanks.

**Comment by wmathurin** [comment]
5.2 has issues with iOS11. They are resolved in the dev branch and will be available in our next release (5.3) which should be available shortly after iOS11 goes live (#safeharbor).

**Comment by CesarRN** [comment]
Hello wmathurin

It´s a problem for me. 

Well, we have to wait for Salesforce.


Thanks.

**Comment by anilabsinc-ajay** [comment]
Not working on xcode 9.3, Unable to complie the project every pod install

**Comment by anilabsinc-ajay** [comment]
@bhariharan  Please update the SDK to support the latest version of the `Cocoapods 1.5.0`

**Comment by bhariharan** [comment]
@anilabsinc-ajay We're waiting on a fix from either `SQLCipher` or `FMDB` for `1.5.0`. Until that, please use `Cocoapods 1.4.0`.
