### ISSUE TITLE
Duplicate symbols when using FMDB via Cocoapods

### ISSUE THREAD

**Issue by paweldudek** [forcedotcom/SalesforceMobileSDK-iOS#1191]
After updating to latest version of SFDC SDK I'm getting duplicate symbols error when trying to compile the app with FMDB as a Cocoapod dependency:

```
duplicate symbol _FMDBExecuteBulkSQLCallback in:
    (...)/Build/Products/Debug-iphoneos/libFMDB.a(FMDatabase.o)
    (...)/Build/Products/Debug-iphoneos/libSalesforceMobileSDK-iOS.a(FMDatabase.o)
ld: 1 duplicate symbol for architecture arm64
```

I see there's some code in pod spec that should take care of namespace clashes for FMDB, however it appears it fails with this particular function.

**Comment by wmathurin** [comment]
In 4.0, we have our own podspec for FMDB (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/blob/master/FMDB/4.0.2/FMDB.podspec) and SmartStore depends on it.
So this issue is no longer relevant.

**Comment by davidpuck** [comment]
I'm sorry to reopen this, but as of 4.2.0 this issue has been introduced again.
I tried with the following podfile:
`source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'SalesforceSDKCore', '~> 4.2.0'
pod 'SalesforceNetwork', '~> 4.2.0'
pod 'SalesforceRestAPI', '~> 4.2.0'
pod 'SmartSync', '~> 4.2.0'
pod 'FMDB', '4.0.2'
pod 'SmartStore', '~> 4.2.0'`

And I got the following error:
[!] Unable to satisfy the following requirements:

- `SQLCipher/fts (~> 3.3.1)` required by `FMDB/FMDB (4.0.2)`
- `SQLCipher/fts (~> 3.4.0)` required by `SmartStore/SmartStore (4.2.0)`

FMDB was not updated to work with 4.2.0

**Comment by davidpuck** [comment]
Sorry to reopen this, but as of version 4.2.0 of the SDK this is still an issue.
Latest version of the SDK (4.2.0) requires a SQL cypher version that is not compatible with latest version of the FMDB podspec (4.0.2)
A podfile like this:

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'SalesforceSDKCore', '~> 4.2'
pod 'SalesforceNetwork', '~> 4.2'
pod 'SalesforceRestAPI', '~> 4.2'
pod 'SmartSync', '~> 4.2'
pod 'FMDB'', '~> 4.0.2'
pod 'SmartStore', '~> 4.2'

Won't even succeed on pod install

**Comment by wmathurin** [comment]
You don't need the pod 'FMDB' line.
Please look at the template podfile here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/build/app_template_files/__NativeTemplateAppName__/Podfile

**Comment by davidpuck** [comment]
Sorry, but with you template, if you try to use FMDB
'#import <FMDB.h>'
You can not even build the project, you get "FMDB.h" file not found

**Comment by wmathurin** [comment]
You don't want to do
```
pod 'FMDB', '4.0.2'
```
Otherwise, you pick up
https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/blob/master/FMDB/4.0.2/FMDB.podspec
Which depends on sqlcipher 3.3.1 while SmartStore 4.2 requires sqlcipher 3.4.

If you do 
```
pod 'FMDB', '2.6.2'
```
You get https://github.com/ccgus/fmdb/blob/master/FMDB.podspec
pod update will not produce any error.

But you will not be able to compile the workspace anymore (because SmartStore is importing FMDB headers that are bundled within). Anyway, I'm reopening the issue.

**Comment by khawkins** [comment]
> because SmartStore is importing FMDB headers that are bundled within

Hmmm, that's why we escape those (exported) symbols as part of the SmartStore.podspec definition.  Sounds like something's not working quite right there?

**Comment by bhariharan** [comment]
This is fixed in `5.0.1` - see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/blob/master/SmartStore/5.0.1/SmartStore.podspec#L27).
